version: "3.9" # Docker version 3.9

services:
  # Api Service
  node:
    image: "node:latest" #Install last version node (https://hub.docker.com/_/node)
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app #Get api file for async image in docker
    ports:
      - 4545:4545 #Open port 4545 at docker
    command: "yarn api" #Launch project

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      ME_CONFIG_MONGODB_URL: "${ME_CONFIG_MONGODB_URL}"

  #FRONT service
  site:
    container_name: site
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./site:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
