version: "3.9" # Docker version 3.9

services:
  node:
    image: "node:latest" #Install last version node (https://hub.docker.com/_/node)
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app #Get api file for async image in docker
    ports:
      - 4545:4545 #Open port 4545 at docker
    command: "yarn api" #Launch project
